name: flash
description: Flash.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+2

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  firebase_core: ^2.20.0
  share_plus: ^7.2.1
  firebase_database: ^10.3.2
  equatable: ^2.0.5
  uuid: ^4.1.0
  auto_route: ^7.8.4
  intl: ^0.18.1
  flutter_localization: ^0.1.14
  firebase_auth: ^4.15.3
  drop_shadow_image: ^0.9.1

dev_dependencies:
  auto_route_generator:
  build_runner:

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true
