name: teacher_review
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  idb_sqflite: ^1.3.2
  get_storage: ^2.1.1
  sqflite: ^2.3.0
  firebase_core: ^2.20.0
  share_plus: ^7.2.1
  auto_size_text: ^3.0.0
  firebase_database: ^10.3.2
  equatable: ^2.0.5
  uuid: ^4.1.0
  auto_route: ^7.8.4

dev_dependencies:
  auto_route_generator:
  build_runner:

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true
